services:
  ig-publisher:
    image: fhir-ig-publisher:test
    build:
      context: .
      dockerfile: Dockerfile.ig-publisher
    volumes:
      - ./test-ig:/usr/src/ig
      - ig-publisher-fhir-cache:/home/igpublisher/.fhir

volumes:
  ig-publisher-fhir-cache:
